const { JSDOM, VirtualConsole } = require('jsdom');
const virtualConsole = new VirtualConsole();
virtualConsole.on('jsdomError', error => { if (!error.message.includes('navigation')) throw error; });
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dom = new JSDOM(fs.readFileSync(path.join(root, 'index.html'), 'utf8'), { url: 'https://indifood.test/', virtualConsole, runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window;
w.scrollTo = () => {};
w.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
w.HTMLDialogElement.prototype.close = function () { this.open = false; };
let sent = [];
let failNextSubmission = false;
w.AbortSignal = global.AbortSignal;
w.fetch = async (url, options) => {
  assert.equal(url, '/api/leads');
  sent.push(JSON.parse(options.body));
  const failed = failNextSubmission;
  failNextSubmission = false;
  return { ok: !failed, json: async () => failed ? { error: 'Please try again.' } : { success: true } };
};
w.eval(fs.readFileSync(path.join(root, 'assets/data/products.js'), 'utf8'));
w.eval(fs.readFileSync(path.join(root, 'assets/js/app.js'), 'utf8'));
const q = selector => w.document.querySelector(selector);
const qa = selector => [...w.document.querySelectorAll(selector)];
async function route(value) { w.location.hash = value; await new Promise(resolve => setTimeout(resolve, 15)); }
(async () => {
  assert.match(q('h1').textContent, /Indifood/);
  assert.equal(qa('.product-card').length, 9);
  assert.equal(qa('.packaging-grid img').length, 0);
  assert.equal(qa('.product-card .has-pack img').length, 9);
  assert.ok(qa('.product-card img').some(img => img.alt.includes('Garlic')));
  assert.equal(q('.mobile-navigation a[aria-current]').dataset.route, '/');
  q('.hero-actions [data-open-enquiry]').click();
  assert.equal(q('#enquiry-popup').open, true);
  q('#close-enquiry-popup').click();
  q('.business-band [data-open-enquiry]').click();
  assert.equal(q('#popup-enquiry-form').elements.type.value, 'Bulk');
  q('#close-enquiry-popup').click();
  await route('/products');
  assert.equal(qa('.product-card').length, 9);
  q('[data-category="Spicy"]').click();
  assert.equal(qa('.product-card').length, 2);
  q('#product-search').value = 'masala';
  q('#product-search').dispatchEvent(new w.Event('input'));
  assert.equal(qa('.product-card').length, 1);
  q('#product-search').value = 'missing flavour';
  q('#product-search').dispatchEvent(new w.Event('input'));
  assert.ok(q('.no-results'));
  q('#reset-filters').click();
  assert.equal(qa('.product-card').length, 9);
  q('.add-product').click();
  assert.equal(q('#basket-count').textContent, '1');
  await route('/product/masala');
  let copiedLink;
  Object.defineProperty(w.navigator, 'clipboard', { configurable: true, value: { writeText: async value => { copiedLink = value; } } });
  q('[data-share-product]').click();
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(copiedLink, 'https://indifood.test/products/masala');
  assert.equal(q('.share-status').textContent, 'Product link copied.');
  Object.defineProperty(w.navigator, 'clipboard', { configurable: true, value: undefined });
  q('[data-share-product]').click();
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(q('.share-fallback').hidden, false);
  assert.equal(q('.share-fallback input').value, 'https://indifood.test/products/masala');
  w.navigator.share = async () => { throw new w.DOMException('Cancelled', 'AbortError'); };
  q('[data-share-product]').click();
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(q('.share-fallback').hidden, true);
  assert.equal(q('[data-share-product]').disabled, false);
  assert.equal(q('#back-to-top').hidden, true);
  w.scrollY = 800;
  w.dispatchEvent(new w.Event('scroll'));
  assert.equal(q('#back-to-top').hidden, false);
  q('#back-to-top').click();
  assert.equal(w.document.activeElement, q('.header .logo'));
  w.scrollY = 0;
  w.dispatchEvent(new w.Event('scroll'));
  assert.equal(q('#back-to-top').hidden, true);
  assert.equal(q('.detail-photo img').getAttribute('src'), 'assets/images/products/spicy-masala.jpg');
  assert.equal(qa('.flavour-option').length, 9);
  assert.equal(q('.flavour-option[aria-current]').dataset.route, '/product/masala');
  assert.equal(q('.mobile-navigation a[aria-current]').dataset.route, '/products');
  q('#product-quantity').value = '3';
  q('.product-enquire').click();
  assert.equal(q('#enquiry-popup').open, true);
  assert.match(q('#popup-enquiry-form').elements.message.value, /3 pack\(s\) of Masala/);
  q('#close-enquiry-popup').click();
  q('#detail-add').click();
  assert.equal(q('#basket-count').textContent, '4');
  q('#mobile-basket').click();
  assert.equal(q('#basket').open, true);
  q('[data-close]').click();
  q('#product-quantity').value = '0';
  q('#detail-add').click();
  assert.equal(q('#basket-count').textContent, '4');
  q('#open-basket').click();
  assert.equal(q('#basket').open, true);
  assert.equal(qa('.basket-row').length, 2);
  q('[data-remove="chatpata"]').click();
  assert.equal(qa('.basket-row').length, 1);
  assert.equal(JSON.parse(w.localStorage.getItem('indifood-basket'))[0].quantity, 3);
  q('#basket-enquire').click();
  assert.equal(q('#basket').open, false);
  assert.equal(q('#enquiry-popup').open, true);
  assert.match(q('#popup-selection').textContent, /Masala \(3 packs\)/);
  const popupForm = q('#popup-enquiry-form');
  popupForm.dispatchEvent(new w.Event('submit', { cancelable: true }));
  assert.equal(sent.length, 0);
  popupForm.elements.name.value = 'Popup Customer';
  popupForm.elements.phone.value = '9876543210';
  popupForm.elements.city.value = 'Pune';
  popupForm.elements.message.value = 'Please share bulk prices.';
  popupForm.elements.packSize.value = '200 g';
  popupForm.querySelector('[type="checkbox"]').checked = true;
  failNextSubmission = true;
  popupForm.dispatchEvent(new w.Event('submit', { cancelable: true }));
  assert.equal(popupForm.querySelector('[type="submit"]').disabled, true);
  popupForm.dispatchEvent(new w.Event('submit', { cancelable: true }));
  assert.equal(sent.length, 1);
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(popupForm.querySelector('[type="submit"]').disabled, false);
  assert.match(popupForm.querySelector('.form-status').textContent, /try again/);
  assert.equal(popupForm.elements.name.value, 'Popup Customer');
  sent = [];
  popupForm.dispatchEvent(new w.Event('submit', { cancelable: true }));
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(sent.length, 1);
  assert.match(popupForm.querySelector('.form-status').textContent, /enquiry has been received/);
  q('#close-enquiry-popup').click();
  assert.equal(q('#enquiry-popup').open, false);
  q('[data-open-enquiry]').click();
  assert.equal(q('#enquiry-popup').open, true);
  assert.equal(popupForm.elements.name.value, 'Popup Customer');
  q('#close-enquiry-popup').click();
  sent = [];
  await route('/contact');
  assert.ok(q('#enquiry-form'));
  assert.equal(q('a.phone-link').getAttribute('href'), 'tel:+919623544741');
  assert.match(q('address').textContent, /Khajmapur.*431512/);
  assert.deepEqual(qa('select[name="packSize"] option').slice(1, 5).map(option => option.value), ['100 g', '200 g', '500 g', '1 kg']);
  assert.match(q('#contact-selection').textContent, /Masala.*3 packs/);
  const form = q('#enquiry-form');
  form.elements.name.value = 'Test Customer';
  form.elements.email.value = 'test@example.com';
  form.elements.city.value = 'Mumbai';
  form.elements.message.value = 'Please confirm pack sizes and prices.';
  form.elements.packSize.value = '500 g';
  q('[type="checkbox"]').checked = true;
  form.dispatchEvent(new w.Event('submit', { cancelable: true }));
  await new Promise(resolve => setTimeout(resolve, 0));
  assert.equal(sent.length, 1);
  assert.equal(sent[0].packSize, '500 g');
  assert.equal(sent[0].consent, true);
  assert.equal(sent[0].formSource, 'contact');
  assert.equal(sent[0].products[0].name, 'Masala');
  assert.match(q('#form-status').textContent, /enquiry has been received/);
  await route('/product/not-real');
  assert.match(q('h1').textContent, /off the menu/);
  for (const page of ['/story', '/faq', '/privacy', '/contact?type=Bulk']) { await route(page); assert.ok(q('h1')); }
  assert.equal(q('select[name="type"]').value, 'Bulk');
  await route('/story');
  for (const content of ['Umesh Babarao Mukke', '2018', 'KVK Tondapur', '11 January 2021', '1,200 sq. ft.', 'Up to 300 kg', '7 women and 3 men', 'Peeling Machine', 'Packing Machine']) assert.ok(q('main').textContent.includes(content), content);
  await route('/quality');
  assert.match(q('main').textContent, /do not reuse previously used cooking oil/);
  assert.equal(qa('.hygiene-list li').length, 5);
  for (const file of ['assets/images/indifood-logo.jpg', 'assets/images/banana-chips.png', 'assets/images/flavour-collection.png', 'assets/vendor/lucide.min.js', 'assets/data/products.js', 'assets/js/app.js', 'assets/css/styles.css']) assert.ok(fs.statSync(path.join(root, file)).size > 0);
  const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
  for (const [, asset] of html.matchAll(/(?:src|href)="(assets\/[^\"]+)"/g)) {
    assert.ok(fs.existsSync(path.join(root, asset)), `Missing HTML asset: ${asset}`);
  }
  const css = fs.readFileSync(path.join(root, 'assets/css/styles.css'), 'utf8');
  for (const [, asset] of css.matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)) {
    assert.ok(fs.existsSync(path.resolve(root, 'assets/css', asset)), `Missing CSS asset: ${asset}`);
  }
  const pages = ['index.html', 'products.html', 'about.html', 'contact.html', 'bulk-orders.html', 'faq.html', 'privacy.html', 'quality.html', 'thank-you.html', '404.html', ...w.INDIFOOD.products.map(p => `products/${p.id}.html`)];
  for (const file of pages) {
    const page = new JSDOM(fs.readFileSync(path.join(root, file), 'utf8'), { url: `https://indifood.test/${file}`, runScripts: 'outside-only' });
    const pw = page.window;
    assert.equal(pw.document.querySelector('link[rel="icon"]').getAttribute('href'), '/assets/images/favicon.svg');
    assert.equal(pw.document.querySelector('meta[property="og:title"]').content, pw.document.title);
    assert.equal(pw.document.querySelector('meta[property="og:description"]').content, pw.document.querySelector('meta[name="description"]').content);
    assert.equal(pw.document.querySelector('meta[name="twitter:card"]').content, 'summary_large_image');
    if (file === '404.html' || file === 'thank-you.html') {
      assert.match(pw.document.querySelector('meta[name="robots"]').content, /noindex/);
    } else {
      const organization = JSON.parse(pw.document.querySelector('script[type="application/ld+json"]').textContent);
      assert.equal(organization.name, 'New Indifood');
      assert.equal(organization.telephone, '+919623544741');
    }
    assert.equal(pw.document.querySelectorAll('main h1').length, 1, `Pre-rendered content: ${file}`);
    pw.scrollTo = () => {};
    pw.localStorage.setItem('indifood-basket', JSON.stringify([{ id: 'masala', quantity: 3 }]));
    pw.eval(fs.readFileSync(path.join(root, 'assets/data/products.js'), 'utf8'));
    pw.eval(fs.readFileSync(path.join(root, 'assets/js/app.js'), 'utf8'));
    assert.equal(pw.document.querySelectorAll('main h1').length, 1, `Rendered page: ${file}`);
    assert.equal(pw.document.getElementById('basket-count').textContent, '3', `Basket restored: ${file}`);
    assert.equal(pw.document.querySelectorAll('a[href^="#/"]').length, 0, `Real page links: ${file}`);
    for (const link of pw.document.querySelectorAll('a[href], img[src], script[src], link[rel="stylesheet"]')) {
      const url = new URL(link.getAttribute('href') || link.getAttribute('src'), pw.document.baseURI);
      if (url.origin === 'https://indifood.test') {
        const target = url.pathname === '/' ? 'index.html' : path.extname(url.pathname) ? url.pathname : url.pathname + '.html';
        assert.ok(fs.existsSync(path.join(root, target)), `Missing target from ${file}: ${url.pathname}`);
        if (link.tagName === 'A') assert.ok(!url.pathname.endsWith('.html'), `Unclean link: ${url.pathname}`);
      }
    }
    if (file === 'contact.html') assert.match(pw.document.getElementById('contact-selection').textContent, /Masala.*3 packs/);
    page.window.close();
  }
  console.log('PASS: all 19 direct HTML pages, prerendered headings, page links, nested assets and cross-page basket restoration.');
  console.log('PASS: nine products; category/search/reset; detail quantities and validation; basket add/remove/persistence; enquiry API submission and retry; all routes; missing product state; local assets.');
  dom.window.close();
})().catch(error => { console.error(error); dom.window.close(); process.exitCode = 1; });
